"""Updated models for docs and proj

Revision ID: c16ab6567a9a
Revises: 65a471d93e06
Create Date: 2026-01-16 03:29:11.595964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c16ab6567a9a'
down_revision: Union[str, Sequence[str], None] = '65a471d93e06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('original_filename', sa.String(length=500), nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('file_type', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('content_type', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='document_status'), nullable=False))
    op.add_column('documents', sa.Column('status_message', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('chunk_count', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('character_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('documents', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('idx_document_project_status', 'documents', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.add_column('projects', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='project_status'), nullable=False))
    op.add_column('projects', sa.Column('chunk_size', sa.Integer(), nullable=False))
    op.add_column('projects', sa.Column('chunk_overlap', sa.Integer(), nullable=False))
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index('idx_project_owner_status', 'projects', ['owner_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_project_owner_status', table_name='projects')
    op.drop_column('projects', 'updated_at')
    op.drop_column('projects', 'chunk_overlap')
    op.drop_column('projects', 'chunk_size')
    op.drop_column('projects', 'status')
    op.drop_column('projects', 'description')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index('idx_document_project_status', table_name='documents')
    op.drop_column('documents', 'processed_at')
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'character_count')
    op.drop_column('documents', 'page_count')
    op.drop_column('documents', 'chunk_count')
    op.drop_column('documents', 'status_message')
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'content_type')
    op.drop_column('documents', 'file_type')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'original_filename')
    # ### end Alembic commands ###
